'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

// 定义支持的语言类型
type Language = 'ko' | 'en' | 'ja' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: keyof typeof translations[Language]) => string
}

// 统一的翻译资源对象
const translations = {
  ko: {
     writing: '글쓰기',
     writingDesc: 'AI 문법 교정, 작문 피드백, 에세이 교정',
     conversation: '대화',
     conversationDesc: '29가지 상황별 대화, 음성 입력, 발음 교정',
     reading: '읽기',
     readingDesc: 'TOEIC/TOEFL/SAT 독해 연습',
     speaking: '말하기',
     speakingDesc: '녹음 연습, 발음 분석, 구두 대화',
     vocabulary: '어휘',
     vocabularyDesc: '간격 반복 학습, CEFR 레벨 단어',
     levelTest: '레벨 테스트',
     levelTestDesc: 'CEFR A1~C2 레벨 테스트',
     metaverse: '메타버스',
     metaverseDesc: '3D 게임화된 학습 경험',
     community: '커뮤니티',
     communityDesc: '학습 후기, Q&A, 리더보드 - 다른 학습자들과 함께 성장하세요',
     subtitle: '7가지 최고의 영어 학습 플랫폼 기능을 통합한 AI 영어 학습 앱',
     subtitle2: '글쓰기, 대화, 읽기, 말하기, 어휘, 테스트, 게임화 - 올인원 플랫폼',
     platformStats: '플랫폼 특징',
     scenarios: '상황별 대화',
     cefrLevels: 'CEFR 레벨',
     integratedFeatures: '통합 기능',
     languages: '지원 언어',
     startLearning: '학습 시작',
     home: '홈',
     writingSubDesc: 'AI 문법 교정, 작문 피드백, 에세이 교정 - 영어 작문 실력 향상',
     writingPlaceholder: '영어 문장이나 단락을 입력하세요',
     writingExample: '예: I go to school yesterday...',
     charCount: '글자 수',
     check: '검사',
     readingSubDesc2: 'TOEIC/TOEFL/SAT 독해 연습 - 영어 읽기 실력 향상',
     testType: '시험 유형',
     general: '일반',
     topic: '주제',
     business: '비즈니스',
     science: '과학',
     technology: '기술',
     culture: '문화',
     academic: '학술',
     recommendedReading: '추천 독해',
     estimatedTime: '예상 시간',
     startReading: '읽기 시작',
     ielts: 'IELTS',
     loading: '로딩 중...',
     noArticlesFound: '문서를 찾을 수 없습니다.',
     tryDifferentFilters: '다른 필터를 선택해보세요.',
     questions: '문제',
     words: '단어',
     conversationSubDesc: '29가지 상황 대화, 음성 입력, 발음 교정 - 영어 대화 능력 향상',
     selectSituation: '상황 선택',
     all: '전체',
     dailyLife: '일상생활',
     travel: '여행',
     learningWork: '학습업무',
     socialActivities: '사교활동',
     emergency: '긴급상황',
     etc: '기타',
     cafe: '카페',
     restaurant: '레스토랑',
     shoppingMall: '쇼핑몰',
     hospital: '병원',
     postOffice: '우체국',
     bank: '은행',
     gym: '헬스장',
     hairSalon: '미용실',
     airport: '공항',
     hotel: '호텔',
     touristSpot: '관광지',
     rentalCar: '렌트카',
     trainStation: '기차역',
     interview: '면접',
     meeting: '회의',
     class: '수업',
     library: '도서관',
     presentation: '발표',
     party: '파티',
     date: '데이트',
     networking: '네트워킹',
     phone: '전화',
     police: '경찰서',
     emergencyRoom: '응급실',
     realEstate: '부동산',
     carRepair: '정비소',
     petHospital: '동물병원',
     selected: '선택됨',
     processing: '처리 중...',
     reset: '초기화',
     speakingSubDesc: '녹음 연습, 발음 분석, 구두 대화 - 영어 말하기 능력 향상',
     allTypes: '모든 유형',
     allDifficulties: '모든 난이도',
     beginner: '초급',
     intermediate: '중급',
     advanced: '고급',
     toeflPhonemePracticeTitle: 'TOEFL 일반 음소 연습',
     toeflPhonemePracticeDesc: '영어에서 가장 일반적인 모음과 자음 발음을 연습하여 음소 정확도를 향상시킵니다.',
     pronunciation: '발음',
     phonemes: '음소',
     estimatedDuration: '예상 시간',
     startPractice: '연습 시작',
     ieltsDailyConversationTitle: 'IELTS 일상 대화 연습',
     ieltsDailyConversationDesc: 'IELTS 말하기 시험의 일상 대화 시나리오를 시뮬레이션하여 구두 표현의 유창성을 향상시킵니다.',
     dailyConversation: '일상 대화',
     businessEnglishPresentationTitle: '비즈니스 영어 발표 연습',
     businessEnglishPresentationDesc: '비즈니스 상황에서의 영어 발표를 연습하여 전문적인 표현 능력을 향상시킵니다.',
     backToList: '목록으로 돌아가기',
     pronunciationPractice: '발음 연습',
     dialoguePractice: '대화 연습',
     presentationPractice: '발표 연습',
     getFeedbackPrompt: '텍스트를 입력하고 "문법 검사"를 클릭하여 피드백을 받으세요',
     feedbackResult: '피드백 결과',
     summary: '요약',
     originalText: '원본',
     correctedText: '수정',
     explanation: '설명',
     vocabularySubDesc: '간격 반복 학습, CEFR 레벨 단어 - 과학적으로 영어 단어 암기',
     allReviewsDone: '오늘의 복습을 모두 완료했습니다!',
     gettingCards: 'AI로부터 어휘 카드를 가져오는 중...',
     showAnswer: '정답 보기',
     next: '다음',
     definition: '정의',
     translation: '번역',
     exampleSentence: '예문',
     mnemonic: '암기 팁',
     levelTestSubDesc: 'CEFR A1~C2 레벨 테스트 - 당신의 영어 실력을 정확하게 평가하세요',
     levelTestInProgress: '레벨 테스트 모듈 개발 중...',
     communityInProgress: '커뮤니티 모듈 개발 중...',
  },
  en: {
    writing: 'Writing',
    writingDesc: 'AI grammar correction, writing feedback, essay polishing',
    conversation: 'Conversation',
    conversationDesc: '29 scenarios, voice input, pronunciation correction',
    reading: 'Reading',
    readingDesc: 'TOEIC/TOEFL/SAT reading practice',
    speaking: 'Speaking',
    speakingDesc: 'Recording practice, pronunciation analysis, oral dialogue',
    vocabulary: 'Vocabulary',
    vocabularyDesc: 'Spaced repetition, CEFR level words',
    levelTest: 'Level Test',
    levelTestDesc: 'CEFR A1~C2 level test',
    metaverse: 'Metaverse',
    metaverseDesc: '3D gamified learning experience',
    community: 'Community',
    communityDesc: 'Learning reviews, Q&A, Leaderboard - Grow with other learners',
    subtitle: 'Integrated AI English Learning Platform combining 7 best features',
    subtitle2: 'Writing, Conversation, Reading, Speaking, Vocabulary, Testing, Gamification - All-in-one platform',
    platformStats: 'Platform Features',
    scenarios: 'Scenarios',
    cefrLevels: 'CEFR Levels',
    integratedFeatures: 'Integrated Features',
    languages: 'Languages',
    startLearning: 'Start Learning',
    home: 'Home',
    writingSubDesc: 'AI grammar correction, writing revision, essay polishing - improve your English writing skills',
    writingPlaceholder: 'Enter your English sentence or paragraph',
    writingExample: 'e.g., I go to school yesterday...',
    charCount: 'Character count',
    check: 'Check',
    readingSubDesc2: 'TOEIC/TOEFL/SAT Reading Practice - Improve Your English Reading Skills',
    testType: 'Test Type',
    general: 'General',
    topic: 'Topic',
    business: 'Business',
    science: 'Science',
    technology: 'Technology',
    culture: 'Culture',
    academic: 'Academic',
    recommendedReading: 'Recommended Reading',
    estimatedTime: 'Estimated time',
    startReading: 'Start Reading',
    ielts: 'IELTS',
    loading: 'Loading...',
    noArticlesFound: 'No articles found.',
    tryDifferentFilters: 'Try selecting different filters.',
    questions: 'Questions',
    words: 'Words',
    conversationSubDesc: '29 situational conversations, voice input, pronunciation correction - improve your English conversation skills',
    selectSituation: 'Select Situation',
    all: 'All',
    dailyLife: 'Daily Life',
    travel: 'Travel',
    learningWork: 'Study/Work',
    socialActivities: 'Social Activities',
    emergency: 'Emergency',
    etc: 'Other',
    cafe: 'Cafe',
    restaurant: 'Restaurant',
    shoppingMall: 'Shopping Mall',
    hospital: 'Hospital',
    postOffice: 'Post Office',
    bank: 'Bank',
    gym: 'Gym',
    hairSalon: 'Hair Salon',
    airport: 'Airport',
    hotel: 'Hotel',
    touristSpot: 'Tourist Spot',
    rentalCar: 'Rental Car',
    trainStation: 'Train Station',
    interview: 'Interview',
    meeting: 'Meeting',
    class: 'Class',
    library: 'Library',
    presentation: 'Presentation',
    party: 'Party',
    date: 'Date',
    networking: 'Networking',
    phone: 'Phone Call',
    police: 'Police Station',
    emergencyRoom: 'Emergency Room',
    realEstate: 'Real Estate',
    carRepair: 'Car Repair',
    petHospital: 'Pet Hospital',
    selected: 'Selected',
    processing: 'Processing...',
    reset: 'Reset',
    speakingSubDesc: 'Recording practice, pronunciation analysis, oral dialogue - improve your English speaking skills',
    allTypes: 'All Types',
    allDifficulties: 'All Difficulties',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    toeflPhonemePracticeTitle: 'TOEFL Common Phoneme Practice',
    toeflPhonemePracticeDesc: 'Practice the most common vowel and consonant sounds in English to improve phonemic accuracy.',
    pronunciation: 'Pronunciation',
    phonemes: 'Phonemes',
    estimatedDuration: 'Estimated duration',
    startPractice: 'Start Practice',
    ieltsDailyConversationTitle: 'IELTS Daily Conversation Practice',
    ieltsDailyConversationDesc: 'Simulate daily conversation scenarios in the IELTS speaking test to improve oral fluency.',
    dailyConversation: 'Daily Conversation',
    businessEnglishPresentationTitle: 'Business English Presentation Practice',
    businessEnglishPresentationDesc: 'Practice English presentations in a business context to improve professional expression skills.',
    backToList: 'Back to List',
    pronunciationPractice: 'Pronunciation Practice',
    dialoguePractice: 'Dialogue Practice',
    presentationPractice: 'Presentation Practice',
    getFeedbackPrompt: "Enter text and click 'Check Grammar' to get feedback",
    feedbackResult: 'Feedback Result',
    summary: 'Summary',
    originalText: 'Original',
    correctedText: 'Corrected',
    explanation: 'Explanation',
    vocabularySubDesc: 'Spaced Repetition, CEFR Level Words - Scientifically memorize English words',
    allReviewsDone: 'All reviews for today are complete!',
    gettingCards: 'Getting vocabulary cards from AI...',
    showAnswer: 'Show Answer',
    next: 'Next',
    definition: 'Definition',
    translation: 'Translation',
    exampleSentence: 'Example Sentence',
    mnemonic: 'Mnemonic',
    levelTestSubDesc: 'CEFR A1~C2 Level Test - Accurately assess your English proficiency',
    levelTestInProgress: 'Level Test module is under development...',
    communityInProgress: 'Community module is under development...',
  },
  ja: {
    writing: 'ライティング',
    writingDesc: 'AI文法チェック、ライティングフィードバック、エッセイ改善',
    conversation: '会話',
    conversationDesc: '29シナリオ、音声入力、発音矯正',
    reading: 'リーディング',
    readingDesc: 'TOEIC/TOEFL/SATリーディング練習',
    speaking: 'スピーキング',
    speakingDesc: '録音練習、発音分析、口頭対話',
    vocabulary: '語彙',
    vocabularyDesc: '間隔反復学習、CEFRレベル単語',
    levelTest: 'レベルテスト',
    levelTestDesc: 'CEFR A1~C2レベルテスト',
    metaverse: 'メタバース',
    metaverseDesc: '3Dゲーミフィケーション学習体験',
    community: 'コミュニティ',
    communityDesc: '学習レビュー、Q&A、リーダーボード - 他の学習者と共に成長しましょう',
    subtitle: '7つの最高機能を統合したAI英語学習プラットフォーム',
    subtitle2: 'ライティング、会話、リーディング、スピーキング、語彙、テスト、ゲーミフィケーション - オールインワンプラットフォーム',
    platformStats: 'プラットフォーム機能',
    scenarios: 'シナリオ',
    cefrLevels: 'CEFRレベル',
    integratedFeatures: '統合機能',
    languages: '言語',
    startLearning: '学習開始',
    home: 'ホーム',
    writingSubDesc: 'AI文法チェック、ライティングフィードバック、エッセイ推敲 - あなたの英語ライティング能力を向上させます',
    writingPlaceholder: '英語の文または段落を入力してください',
    writingExample: '例: I go to school yesterday...',
    charCount: '文字数',
    check: 'チェック',
    readingSubDesc2: 'TOEIC/TOEFL/SAT読解練習 - 英語読解力向上',
    testType: '試験タイプ',
    general: '一般',
    topic: 'トピック',
    business: 'ビジネス',
    science: '科学',
    technology: 'テクノロジー',
    culture: '文化',
    academic: '学術',
    recommendedReading: 'おすすめの読解',
    estimatedTime: '予想時間',
    startReading: '読み始める',
    ielts: 'IELTS',
    loading: '読み込み中...',
    noArticlesFound: '記事が見つかりません。',
    tryDifferentFilters: '別のフィルターを選択してみてください。',
    questions: '問題',
    words: '単語',
    conversationSubDesc: '29の状況別会話、音声入力、発音矯正 - あなたの英会話能力を向上させます',
    selectSituation: '状況を選択',
    all: 'すべて',
    dailyLife: '日常生活',
    travel: '旅行',
    learningWork: '学習・業務',
    socialActivities: '社会活動',
    emergency: '緊急事態',
    etc: 'その他',
    cafe: 'カフェ',
    restaurant: 'レストラン',
    shoppingMall: 'ショッピングモール',
    hospital: '病院',
    postOffice: '郵便局',
    bank: '銀行',
    gym: 'ジム',
    hairSalon: '美容院',
    airport: '空港',
    hotel: 'ホテル',
    touristSpot: '観光地',
    rentalCar: 'レンタカー',
    trainStation: '駅',
    interview: '面接',
    meeting: '会議',
    class: '授業',
    library: '図書館',
    presentation: '発表',
    party: 'パーティー',
    date: 'デート',
    networking: 'ネットワーキング',
    phone: '電話',
    police: '警察署',
    emergencyRoom: '救急治療室',
    realEstate: '不動産',
    carRepair: '整備工場',
    petHospital: '動物病院',
    selected: '選択済み',
    processing: '処理中...',
    reset: 'リセット',
    speakingSubDesc: '録音練習、発音分析、口頭対話 - あなたの英語スピーキング能力を向上させます',
    allTypes: 'すべてのタイプ',
    allDifficulties: 'すべての難易度',
    beginner: '初級',
    intermediate: '中級',
    advanced: '上級',
    toeflPhonemePracticeTitle: 'TOEFL 一般的な音素の練習',
    toeflPhonemePracticeDesc: '英語で最も一般的な母音と子音の発音を練習し、音素の正確さを向上させます。',
    pronunciation: '発音',
    phonemes: '音素',
    estimatedDuration: '予想時間',
    startPractice: '練習を始める',
    ieltsDailyConversationTitle: 'IELTS 日常会話の練習',
    ieltsDailyConversationDesc: 'IELTSスピーキングテストの日常会話シナリオをシミュレートし、口頭表現の流暢さを向上させます。',
    dailyConversation: '日常会話',
    businessEnglishPresentationTitle: 'ビジネス英語プレゼンテーション練習',
    businessEnglishPresentationDesc: 'ビジネスシーンでの英語プレゼンテーションを練習し、専門的な表現能力を向上させます。',
    backToList: 'リストに戻る',
    pronunciationPractice: '発音練習',
    dialoguePractice: '対話練習',
    presentationPractice: 'プレゼンテーション練習',
    getFeedbackPrompt: 'テキストを入力して「文法チェック」をクリックするとフィードバックが得られます',
    feedbackResult: 'フィードバック結果',
    summary: '概要',
    originalText: '原文',
    correctedText: '修正',
    explanation: '説明',
    vocabularySubDesc: '間隔反復学習、CEFRレベル単語 - 科学的に英単語を記憶',
    allReviewsDone: '今日の復習はすべて完了しました！',
    gettingCards: 'AIから語彙カードを取得中...',
    showAnswer: '答えを見る',
    next: '次へ',
    definition: '定義',
    translation: '翻訳',
    exampleSentence: '例文',
    mnemonic: '記憶術',
    levelTestSubDesc: 'CEFR A1～C2レベルテスト - あなたの英語能力を正確に評価します',
    levelTestInProgress: 'レベルテストモジュールは開発中です...',
    communityInProgress: 'コミュニティモジュールは開発中です...',
  },
  zh: {
    writing: '写作模块',
    writingDesc: 'AI语法纠错、写作批改、作文润色',
    conversation: '对话模块',
    conversationDesc: '29种情境对话、语音输入、发音纠错',
    reading: '阅读模块',
    readingDesc: 'TOEIC/TOEFL/SAT阅读训练',
    speaking: '口语模块',
    speakingDesc: '录音练习、发音分析、口语对话',
    vocabulary: '词汇模块',
    vocabularyDesc: '间隔重复学习、CEFR级别词汇',
    levelTest: '级别测试',
    levelTestDesc: 'CEFR A1~C2级别测试',
    metaverse: '元宇宙',
    metaverseDesc: '3D游戏化学习体验',
    community: '社区',
    communityDesc: '学习后记、Q&A问答、排行榜 - 与其他学习者一起进步',
    subtitle: '整合了7个最佳英语学习平台功能的综合性AI英语学习应用',
    subtitle2: '写作、对话、阅读、口语、词汇、测试、游戏化 - 一站式英语学习平台',
    platformStats: '平台特色',
    scenarios: '情境对话',
    cefrLevels: 'CEFR级别',
    integratedFeatures: '整合功能',
    languages: '语言支持',
    startLearning: '开始学习',
    home: '首页',
    writingSubDesc: 'AI语法纠错、写作批改、作文润色 - 提升你的英语写作能力',
    writingPlaceholder: '输入你的英文句子或段落',
    writingExample: '例如: I go to school yesterday...',
    charCount: '字符数',
    check: '检查',
    readingSubDesc2: 'TOEIC/TOEFL/SAT 阅读练习 - 提升你的英语阅读能力',
    testType: '考试类型',
    general: '通用',
    topic: '主题',
    business: '商务',
    science: '科学',
    technology: '科技',
    culture: '文化',
    academic: '学术',
    recommendedReading: '推荐阅读',
    estimatedTime: '预计用时',
    startReading: '开始阅读',
    ielts: '雅思',
    loading: '加载中...',
    noArticlesFound: '未找到任何文章。',
    tryDifferentFilters: '请尝试选择不同的筛选条件。',
    questions: '问题',
    words: '单词',
    conversationSubDesc: '29种情景对话、语音输入、发音校正 - 提升您的英语会话能力',
    selectSituation: '选择情景',
    all: '全部',
    dailyLife: '日常生活',
    travel: '旅行',
    learningWork: '学习/工作',
    socialActivities: '社交活动',
    emergency: '紧急情况',
    etc: '其他',
    cafe: '咖啡馆',
    restaurant: '餐厅',
    shoppingMall: '购物中心',
    hospital: '医院',
    postOffice: '邮局',
    bank: '银行',
    gym: '健身房',
    hairSalon: '理发店',
    airport: '机场',
    hotel: '酒店',
    touristSpot: '旅游景点',
    rentalCar: '租车',
    trainStation: '火车站',
    interview: '面试',
    meeting: '会议',
    class: '课堂',
    library: '图书馆',
    presentation: '发表',
    party: '派对',
    date: '约会',
    networking: '社交',
    phone: '打电话',
    police: '警察局',
    emergencyRoom: '急诊室',
    realEstate: '房产中介',
    carRepair: '汽修店',
    petHospital: '宠物医院',
    selected: '已选择',
    processing: '处理中...',
    reset: '重置',
    speakingSubDesc: '录音练习、发音分析、口语对话 - 提升你的英语口语能力',
    allTypes: '所有类型',
    allDifficulties: '所有难度',
    beginner: '初级',
    intermediate: '中级',
    advanced: '高级',
    toeflPhonemePracticeTitle: 'TOEFL 常见音素练习',
    toeflPhonemePracticeDesc: '练习英语中最常见的元音和辅音发音，提高音素准确度。',
    pronunciation: '发音',
    phonemes: '音素',
    estimatedDuration: '预计时长',
    startPractice: '开始练习',
    ieltsDailyConversationTitle: 'IELTS 日常对话练习',
    ieltsDailyConversationDesc: '模拟IELTS口语考试中的日常对话场景，提高口语表达流畅度。',
    dailyConversation: '日常对话',
    businessEnglishPresentationTitle: '商务英语演讲练习',
    businessEnglishPresentationDesc: '练习商务场景下的英语演讲，提高专业表达能力。',
    backToList: '返回任务列表',
    pronunciationPractice: '发音练习',
    dialoguePractice: '对话练习',
    presentationPractice: '演讲练习',
    getFeedbackPrompt: '输入文本后点击“检查语法”获取反馈',
    feedbackResult: '反馈结果',
    summary: '总结',
    originalText: '原文',
    correctedText: '修正后',
    explanation: '说明',
    vocabularySubDesc: '间隔重复学习、CEFR级别词汇 - 科学记忆英语单词',
    allReviewsDone: '今日已完成所有复习！',
    gettingCards: '正在从AI获取词汇卡片...',
    showAnswer: '显示答案',
    next: '下一个',
    definition: '定义',
    translation: '翻译',
    exampleSentence: '例句',
    mnemonic: '助记',
    levelTestSubDesc: 'CEFR A1~C2级别测试 - 准确评估你的英语水平',
    levelTestInProgress: '级别测试模块开发中...',
    communityInProgress: '社区模块开发中...',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ko')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language
    if (saved && ['ko', 'en', 'ja', 'zh'].includes(saved)) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t: (key: keyof typeof translations[Language]) => translations[language][key] || key,
      }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
  // 默认使用韩语
  return {
    language: 'ko' as Language,
    setLanguage: () => {},
    t: (key: keyof typeof translations['ko']) => translations.ko[key] || key,
  }
  }
  return context
}
